name: 'OPA Checkpoints'
description: 'Add Checkpoints controlled by OPA into your workflows'
inputs:
  tenant:  # id of input
    description: 'Tenant to call OPA against (e.g. http://<tenant name>.styra.com)'
    required: true
  api-token:  # id of input
    description: 'DAS API token to use when calling tenant'
    required: true
  system-id:  # id of input
    description: 'DAS System id being used'
    required: true
  rule:  # id of input
    description: 'Rule to call'
    required: true
    default: "rules/main"

outputs:
  results: 
    description: 'The results from OPA'
runs:
  using: 'node16'
  main: 'dist/index.js'