on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run OPA Checkpoint
    steps:
      - name: first checkpoint
        id: hello
        uses: kroekle/opa-checkpoint-action@v1.1.3
        with:
          tenant: ${secrets.DAS_TENANT}
      - name: Get the output messages
        run: echo "The messages are ${{ steps.hello.outputs.messages }}"
