on: [push]

jobs:
  hello_world_job:
    env:
      tenant: ${{secrets.DAS_TENANT}}
      system_id: ${{secrets.DAS_SYSTEM_ID}}
      token: ${{secrets.DAS_API_TOKEN}}
    runs-on: ubuntu-latest
    name: Run OPA Checkpoint
    steps:
      - name: first checkpoint
        id: hello
        uses: kroekle/opa-checkpoint-action@v1.1.12
        with:
          tenant: ${{env.tenant}}
          system-id: ${{env.system_id}}
          api-token: ${{env.token}}
      - name: Get the output messages
        run: echo "The messages are ${{ steps.hello.outputs.messages }}"
