on: [push, pull_request]

jobs:
  hello_world_job:
    env:
      tenant: "https://kurt.styra.com"
      system_id: "e447b48d6c764bb3bfee25809647aefb"
      token: ${{secrets.DAS_API_TOKEN}}
    runs-on: ubuntu-latest
    name: Run OPA Checkpoint
    steps:
      - name: first checkpoint
        id: hello
        uses: kroekle/opa-checkpoint-action@v1.1.33
        with:
          tenant: ${{env.tenant}}
          system-id: ${{env.system_id}}
          api-token: ${{env.token}}
      - name: Get the output messages
        run: echo "The messages are ${{ steps.hello.outputs.messages }}"
      - name: Get the result
        run: echo "The result is ${{ steps.hello.outputs.results }}"
